In [2]:
import numpy as np


### 1. Create an array of integers from 2 to 20 with a step of 2 (Marks: 1)


In [3]:
arr = np.arange(2,21,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


### 2. Find the minimum values for each row of below array. Output should be array of 4 values. (Marks: 1)


In [5]:
arr = np.array([[110, 102, 183],
                     [140, 175, 106],
                     [170, 195, 117],
                     [192, 140, 195]])

minval = np.min(arr,axis=1)
minval

array([102, 106, 117, 140])

### 3. Replace all numbers in array, 'arr', that are less than 10 with -2.    (Marks: 2)


In [7]:
arr = np.array([0,5,6,7,8,10,12,13])
arr[arr<10] = -2
print(arr)

[-2 -2 -2 -2 -2 10 12 13]


### 4. Replace all even numbers in 'arr' with 2, by creating a new array called 'arr2' and retaining the original array 'arr' (Marks: 2)


In [13]:
arr = np.array([0, 31, 42, 43, 34, 45])

arr2[arr%2==0] = 2
print(arr2)

arr = arr.copy()
print(arr)


[ 2 31  2 43  2 45]
[ 0 31 42 43 34 45]


### 5. Create 2 arrays as shown below and stack them vertically, A on top of B (Mark: 2)


$$  A = \left( \begin{array}{cc} 1 & 2 & 3 \\ 3 & 1 & 2 \end{array}\right)  B = \left( \begin{array}{cc} 1 & 4 & 1 \\ 2 & 5 & 2 \\ 4 & 2 & 8 \end{array}\right) $$

In [20]:
A = np.array([[1,2,3],
             [3,1,2]])

B = np.array([[1,4,1],
             [2,5,2],
              [4,2,8]])

print("Vertical stacking A on top of B = \n", np.vstack((A,B)))

Vertical stacking A on top of B = 
 [[1 2 3]
 [3 1 2]
 [1 4 1]
 [2 5 2]
 [4 2 8]]


### 6. Get the index positions where elements of below two arrays match (Mark: 1)


In [23]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

print("Index positions of elements that match = ", np.where(array1 == array2))

Index positions of elements that match =  (array([1, 3, 5, 7], dtype=int64),)


### 7. Find the mean, median and standard deviation down each column for the given table. There should be 9 values as outputs for each. (Mark: 2)
$$ Data = \left( \begin{array}{cc} 1, & 4, & 5, & 4, & 6, & 4 & 7 & 1 & 2\\ 1, & 1, & 0, & 0, & 0, & 0 & 0 & 0 & 1 \\ 1, & 4, & 5, & 4, & 6, & 4 & 7 & 1 & 2 \\ 11, & 4, & 5, & 8, & 9, & 10 & 2 & 1 & 3\end{array}\right) $$

In [24]:
data = np.array([[1,4,5,4,6,4,7,1,2],[1,1,0,0,0,0,0,0,1],[1,4,5,4,6,4,7,1,2],[11,4,5,8,9,10,2,1,3]])

def stats(data):
    return np.mean(data, axis=0), np.median(data, axis=0), np.std(data, axis=0)

stats(data)

(array([3.5 , 3.25, 3.75, 4.  , 5.25, 4.5 , 4.  , 0.75, 2.  ]),
 array([1. , 4. , 5. , 4. , 6. , 4. , 4.5, 1. , 2. ]),
 array([4.33012702, 1.29903811, 2.16506351, 2.82842712, 3.26917421,
        3.57071421, 3.082207  , 0.4330127 , 0.70710678]))

### 8. Use masking to get the elements from 'data' smaller than 10 in entire column index 1. (Marks: 1)


In [25]:
data = np.arange(16).reshape(4,4)
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [28]:
mask = data[:, 1] <10

data[mask,1]

array([1, 5, 9])

### 9. Create Array A (the one on top) as shown. Use fancy indexing to change it to array A below (Mark: 2)


$$  A = \left( \begin{array}{cc} 1 & 2 & 3 \\ 3 & 1 & 2 \end{array}\right) $$ 
$$ A = \left( \begin{array}{cc} 1 & 4 & 3 \\ 6 & 1 & 9 \end{array}\right) $$

In [38]:
A = np.array([[1,2,3],[3,1,2]])
A

A[0,[1]] = 4
A[1,[0,2]] = 6,9
A

array([[1, 4, 3],
       [6, 1, 9]])